/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'DeductInventoryOnAccept': EventHandler<never, never>
    'CustomerGetOrder': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CustomerGetMenu': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; menu: Array<{ name: string; description?: string; price: number; category: string; preparationTime?: number; imageUrl?: string; available: boolean }>; total: number }>, never>
    'CustomerGetOrders': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CustomerPlaceOrder': ApiRouteHandler<{ items: Array<{ dishName: string; quantity: number }> }, unknown, never>
    'AdminUpdateOrderStatus': ApiRouteHandler<{ newStatus: 'accepted' | 'rejected' | 'preparing' | 'ready' | 'completed' | 'cancelled'; adminMessage: string }, unknown, { topic: 'order.accepted'; data: never }>
    'AdminUpdateIngredient': ApiRouteHandler<{ name?: string; unit?: string; quantity?: number; reorderLevel?: number; cost?: number }, unknown, never>
    'AdminUpdateDish': ApiRouteHandler<{ name?: string; description?: string; price?: number; category?: string; preparationTime?: number; imageUrl?: string; available?: boolean }, unknown, never>
    'AdminGetIngredients': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; ingredients: Array<{ name: string; unit: string; quantity: number; reorderLevel?: number; cost?: number; createdAt: string; updatedAt: string }>; total: number }> | ApiResponse<401, { error: string }> | ApiResponse<403, { error: string }>, never>
    'GetAdminDashboard': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAllOrders': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AdminDeleteIngredient': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AdminDeleteDish': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AdminAIAnalytics': ApiRouteHandler<{ query: string }, unknown, never>
    'AdminAddIngredient': ApiRouteHandler<{ name: string; unit: string; quantity: number; reorderLevel?: number; cost?: number }, unknown, never>
    'AdminAddDish': ApiRouteHandler<{ name: string; description?: string; price: number; category: string; ingredients: Array<{ ingredientId: string; quantity: number }>; preparationTime?: number; available: boolean; imageUrl?: string }, unknown, never>
  }
    interface StreamAuthContext { userId: string; isAdmin: boolean }
}